###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/refresh/impl/hbm_per_bank_refresh.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component


class HBMPerBankRefresh(Component):
    impl = "HBMPerBankRefresh"
