###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/atomic_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child


class Atomic(Component):
    impl = "Atomic"
    latency = Param(int, default=-1)
    read_buffer_size = Param(int, default=64)
    write_buffer_size = Param(int, default=64)
    refresh = Param(str, default='none')
    trace_path = Param(str, default='')
    addr_mapper = Child("addr_mapper")
    dram = Child("dram")
