###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/fixed_lat_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child


class FixedLat(Component):
    impl = "FixedLat"
    latency = Param(int, default=-1)
    pipe = Param(int, default=1)
    trace_path = Param(str, default='')
    dram = Child("dram")
