###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/wmg1_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child


class WMG1(Component):
    impl = "WMG1"
    window_ns = Param(int, default=10000)
    trace_path = Param(str, default='')
    dram = Child("dram")
