###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/memory_trace/synthetic_pattern.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class SyntheticPattern(Component):
    impl = "SyntheticPattern"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    num_requests = Param(int, required=True)
    streams = Param(int, default=1)
    stream_params = Param(str, default='')
    mode_switch = Param(int, default=0)
    mode_b = Param(str, default='')
    share_region = Param(bool, default=False)
    mlp = Param(int, default=16)
    dep_frac = Param(float, default=0.0)
    think_time = Param(int, default=0)
    jitter = Param(int, default=0)
    row_run = Param(int, default=32)
    bank_spread = Param(int, default=1)
    bank_random = Param(bool, default=False)
    row_random = Param(bool, default=False)
    wfrac_pct = Param(int, default=0)
    wb_mode = Param(int, default=0)
    wb_batch = Param(int, default=1)
    phase_on = Param(int, default=0)
    phase_off = Param(int, default=0)
    phase_off_random = Param(int, default=0)
    pp_lead = Param(int, default=40)
    seed = Param(int, default=1, cpp_type="uint64_t")
    addr_vec_size = Param(int, required=True)
    total_bank_units = Param(int, required=True)
    row_pos = Param(int, required=True)
    col_pos = Param(int, required=True)
    num_rows = Param(int, required=True)
    num_cols = Param(int, required=True)
    internal_prefetch_size = Param(int, required=True)
    num_cls = Param(int, required=True)
    bank_positions = Param(list, required=True, cpp_type="std::vector<int>")
    bank_counts = Param(list, required=True, cpp_type="std::vector<int>")
