###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Regenerate:   python -m ramulator codegen
###############################################################################
from .no_translation import NoTranslation
from .random_translation import RandomTranslation

__all__ = ['NoTranslation', 'RandomTranslation']
