###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/translation/impl/random_translation.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class RandomTranslation(Component):
    impl = "RandomTranslation"
    max_addr = Param(int, required=True, cpp_type="Addr_t")
    page_size = Param(int, default=4096, cpp_type="Addr_t")
