###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/md1_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child


class MD1(Component):
    impl = "MD1"
    phase_ticks = Param(int, default=10000)
    smoothing = Param(float, default=0.5)
    trace_path = Param(str, default='')
    dram = Child("dram")
