###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/impl/mess_controller.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, Child


class Mess(Component):
    impl = "Mess"
    curve_path = Param(str, required=True)
    window_accesses = Param(int, default=1000)
    converge = Param(float, default=0.05)
    trace_path = Param(str, default='')
    dram = Child("dram")
